export const SET_INITIAL_STATE = 'SET_INITIAL_STATE'

export const ADD_IMAGE = 'ADD_IMAGE'
export const ADD_TEXT = 'ADD_TEXT'
export const ADD_LINE = 'ADD_LINE'

export const UPDATE_IMAGE_POSITION = 'UPDATE_IMAGE_POSITION'
export const UPDATE_IMAGE_DIMENSIONS = 'UPDATE_IMAGE_DIMENSIONS'

export const UPDATE_TEXT_POSITION = 'UPDATE_TEXT_POSITION'
export const UPDATE_TEXT_DIMENSIONS = 'UPDATE_TEXT_DIMENSIONS'
export const UPDATE_TEXT_CONTENT = 'UPDATE_TEXT_CONTENT'
export const UPDATE_TEXT_FONT_FAMILY = 'UPDATE_TEXT_FONT_FAMILY'
export const UPDATE_TEXT_FONT_SIZE = 'UPDATE_TEXT_FONT_SIZE'

export const UPDATE_LINE_POINTS = 'UPDATE_LINE_POINTS'
export const UPDATE_LINE_COLOR = 'UPDATE_LINE_COLOR'
export const UPDATE_LINE_WIDTH = 'UPDATE_LINE_WIDTH'

export const DELETE_LINE = 'DELETE_LINE'
export const DELETE_TEXT = 'DELETE_TEXT'
export const DELETE_IMAGE = 'DELETE_IMAGE'

export const IMAGE_SELECTION = 'IMAGE_SELECTION'
export const TEXT_SELECTION = 'TEXT_SELECTION'
export const LINE_SELECTION = 'LINE_SELECTION'
