export const ADD_IMAGE = 'ADD_IMAGE'
export const ADD_TEXT = 'ADD_TEXT'
export const UPDATE_IMAGE_POSITION = 'UPDATE_IMAGE_POSITION'
export const UPDATE_TEXT_POSITION = 'UPDATE_TEXT_POSITION'
export const UPDATE_IMAGE_DIMENSIONS = 'UPDATE_IMAGE_DIMENSIONS'
export const UPDATE_TEXT_DIMENSIONS = "UPDATE_TEXT_DIMENSIONS"
export const UPDATE_TEXT_CONTENT = "UPDATE_TEXT_CONTENT"


export const IMAGE_SELECTION = 'IMAGE_SELECTION'
export const TEXT_SELECTION = 'TEXT_SELECTION'
export const LINE_SELECTION = 'LINE_SELECTION'
